<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Dart Analysis Output</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>analysis.severity.error.dart-analysis-output</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>message.dart-analysis-output</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>analysis.type.dart-analysis-output</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>file.name.dart-analysis-output</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>row.dart-analysis-output</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>column.dart-analysis-output</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(ERROR)(\|)(\w+)(\|)(.+)(\|)(\d+)(\|)(\d+)(\|)(.+)$</string>
			<key>name</key>
			<string>analysis.result.dart-analysis-output</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>analysis.severity.warning.dart-analysis-output</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>message.dart-analysis-output</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>analysis.type.dart-analysis-output</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>file.name.dart-analysis-output</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>row.dart-analysis-output</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>column.dart-analysis-output</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(WARNING)(\|)(\w+)(\|)(.+)(\|)(\d+)(\|)(\d+)(\|)(.+)$</string>
			<key>name</key>
			<string>analysis.result.dart-analysis-output</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>analysis.severity.info.dart-analysis-output</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>message.dart-analysis-output</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>analysis.type.dart-analysis-output</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>file.name.dart-analysis-output</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>row.dart-analysis-output</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>column.dart-analysis-output</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(INFO)(\|)(\w+)(\|)(.+)(\|)(\d+)(\|)(\d+)(\|)(.+)$</string>
			<key>name</key>
			<string>analysis.result.dart-analysis-output</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>analysis.severity.unknown.dart-analysis-output</string>
				</dict>
				<key>10</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>11</key>
				<dict>
					<key>name</key>
					<string>message.dart-analysis-output</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>analysis.type.dart-analysis-output</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>file.name.dart-analysis-output</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>row.dart-analysis-output</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>field.separator.dart-analysis-output</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>column.dart-analysis-output</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\w+)(\|)(\w+)(\|)(.+)(\|)(\d+)(\|)(\d+)(\|)(.+)$</string>
			<key>name</key>
			<string>analysis.result.dart-analysis-output</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.dart-analysis-output</string>
</dict>
</plist>
