<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>pubspec.yaml</string>
	</array>
	<key>name</key>
	<string>Pubspec</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.yaml</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.pubspec</string>
	<key>uuid</key>
	<string>6ee48569-820e-4e1f-9f5c-71ed9516ecc5</string>
</dict>
</plist>
